In [1]:
import numpy as np

<b>Tip</b>: By default np.sort uses an NLogN

In [5]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

# in-place sorting
x.sort()
x

array([1, 2, 3, 4, 5])

In [13]:
# We can only only indices of the items that will be, after sorting

y = np.array([5, 4, 3, 2, 1])
i = np.argsort(y)

# Now you want to sort the array, we can use Fancy Indexing with the above indices.
y[i]

# Our original array is still in the original state.

array([5, 4, 3, 2, 1])

<h2 style="color:black;font-weight:bold;font-family:Georgia">Sorting along rows & columns</h2>

In [22]:
z = np.random.randint(1, 10, (3, 4))
print("Original Array")
print(z)

print("Sorted by row")
print(np.sort(z, axis=1)) # Sort every row.

print("Sorted by Column")
print(np.sort(z, axis=0))

Original Array
[[5 9 9 2]
 [7 6 4 2]
 [2 1 5 3]]
Sorted by row
[[2 5 9 9]
 [2 4 6 7]
 [1 2 3 5]]
Sorted by Column
[[2 1 4 2]
 [5 6 5 2]
 [7 9 9 3]]


<h2 style="color:black;font-weight:bold;font-family:Georgia">Partial Sorting</h2>
<p>Sometimes we are not interesed in sorting the complete array.</p>

In [38]:
arr_1d = np.random.randint(1, 100, 10)
print(arr_1d)

# Let's assume we want only the 1st 5 values out of 10, to be sorted.
# We can use numpy partition which accepts an array and a K constant

# Result will be, K(=3 e.g) will be the smallest 3 values in the array. So the array
# is partitioned in two parts [:3, 3:]
# Both the parts are still not sorted. They can be in any order.

np.partition(arr_1d, 3)

# The same can be done to a multi-dim array. 
# And a np.argpartiotion also exists.

[89 46 81 23 77 61 74 50 81 43]


array([43, 23, 46, 50, 61, 74, 77, 81, 81, 89])