<h1>Structured arrays</h1>

<p>These can be used to store multi type information in a single structure </p>

<p>Lets say, we want to store data about people. Their name, age, and weight.</p>
<p>If we store each attribute in a list, it will be difficult to relate them with each other</p>
<p>E.g, name = ['adam', 'joe', 'steve'], age = [32, 45, 21], weight = [67, 78, 55]</p>

In [1]:
import numpy as np

In [29]:
# We can do a better job using numpy structure arrays.

# Till now we have created arrays like this:
np.zeros(4, dtype=int)

# We can similarly create arrays using some custom dtypes.
# Note: The keys are mandatorily names and formats. It CANNOT be anything else.

my_dtype = {
            'names': ('name', 'age', 'weight'),
            'formats':(str, int, float)
           }

np.zeros(4, dtype=my_dtype)


array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U'), ('age', '<i8'), ('weight', '<f8')])


<h2>Above we constructed a dtype of our own.</h2>
<h3>Note: The dict keys have to be "names" and "formats".</h3>

<h3>We have used some formats here. These are all build-in python formats.</h3>
<ul>
    <li>str</li>
    <li>int</li>
    <li>float</li>
</ul>

<h2>Numpy offers are few more formats</h2>
<p>Lets use them</p>

In [21]:
# U10 -> Unicode - Max length 10.
# i4 -> Integer - 4 bytes (32 bits) max.
# f8 -> Float - 8 byte (64 bit) max.

my_dtype = {
            'names': ('name', 'age', 'weight'),
            'formats':('U10', 'i4', 'f8')
           }

people = np.zeros(3, dtype=my_dtype)

# Let create some people and fill our people array with some data.

name = ['adam', 'joe', 'steve']
age = [32, 45, 21]
weight = [67, 78, 55]

people['name'] = name
people['age'] = age
people['weight'] = weight

people

['adam' 'joe' 'steve']
('adam', 32, 67.)


<h3>Lets try some querying and computations using our newly populated data array</h3>

In [28]:
# Get all names.
print(people['name'])

# Get first person (whoever that is)
print(people[0])

# Get the names of persons whose weight is more than 70kg (hope my name doesn't come up)
print(
    people[
        people['weight'] >= 70 # This here is our boolean mask.
    ]['name']
)

['adam' 'joe' 'steve']
('adam', 32, 67.)
['joe']


<h2>Other ways to create formats</h2>

In [42]:
# Create tuples of title and type.
my_types_as_tuple = np.dtype([('name', 'U10'), ('age', 'i4'), ('weight', 'f8')])

# Using numpy types available.
my_types_mixed = np.dtype(
                {
                    'names':('name', 'age', 'weight'),
                    'formats':((np.str_, 10), np.int32, np.float32)
                })

# Probably the simplest way: String with comma separated types.
my_types_shortest = np.dtype('U10,i4,f8')
my_types_shortest

# The < and > symbols long with the types indicate little endian or big endian respectively.

dtype([('f0', '<U10'), ('f1', '<i4'), ('f2', '<f8')])

```
Character	Description	            Example
'b'	        Byte	                np.dtype('b')
'i'	        Signed integer	        np.dtype('i4') == np.int32
'u'	        Unsigned integer        np.dtype('u1') == np.uint8
'f'	        Floating point	        np.dtype('f8') == np.int64
'c'	        Complex floating point	np.dtype('c16') == np.complex128
'S','a'	    String	                np.dtype('S5')
'U'	        Unicode string	        np.dtype('U') == np.str_
'V'	        Raw data (void)	        np.dtype('V') == np.void
```

<h2>Advanced Compound Types</h2>
<p>We can create other complex type of dtypes. Example, we can create a matrix type of dtype.</p>

In [44]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)

print(X[0])
print(X['mat'][0])

[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<h2 style="color:black;font-weight:normal;font-family:Georgia">One Last thing. We saw that arrays can access its contents with a key style access array[key].</h2>
<h2 style="color:black;font-weight:normal;font-family:Georgia">We can also go for a property style approach.</h2>
<p>array.key</p>

In [46]:
people_as_props = people.view(np.recarray)
people_as_props.age

array([32, 45, 21], dtype=int32)