In [1]:
import numpy
import numpy as np

In [2]:
numpy.__version__

'1.20.2'

<h3 style='color:black;font-weight:normal;font-family:Georgia'># You can create arrays also with arrays module. </h3>

In [3]:
# This is one way to create efficient arrays, but ndarray is much better.

import array
array.array('i', range(10, 100, 10))

array('i', [10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
# Using numpy arrays
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

<h3 style='color:black;font-weight:normal;font-family:Georgia'># If all members of array are NOT of same type, they auto upcast</h3>

In [5]:
np.array([1.5,1,2,3,4])

array([1.5, 1. , 2. , 3. , 4. ])

In [6]:
# In this case, since a str is present, all item will auto cast to string.
np.array([1, 2,'3', 4, 5])

array(['1', '2', '3', '4', '5'], dtype='<U21')

<h2 
    style='color:black;text-shadow: 1px 1px #000000;font-weight:normal;font-family:Georgia;border-style: solid;padding:10px;'># Lets create arrays of different types</h2>

In [7]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# 2d array: 3 rows 2 columns array
np.zeros((3,2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [9]:
# 2d array with ones
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
# Array with all rows & columns full of the same object.
np.full((3,2), 5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [11]:
# Array with each row same as items.
np.full((3, 2), ['a', 'b'])

array([['a', 'b'],
       ['a', 'b'],
       ['a', 'b']], dtype='<U1')

In [39]:
# Numpy also has a range similar to python range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Range with Step.
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
# linspace creates an array of N items distributed using a lower and upper range.
np.linspace(10, 30, 5)

array([10., 15., 20., 25., 30.])

In [15]:
# Create an identity matrix using "eye".
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# empty
np.empty(5)

array([10., 15., 20., 25., 30.])

<h2 style="color:black;font-weight:normal;font-family:Georgia">Standard Deviation is the amount of variation in a set of values</h2>
<ul>
    <li>Mean can be imagined as, the expected value.</li>
    <li>The lower the standar deviation, the closer it is, to the mean.</li>
</ul>

<h3 style="color:black;font-weight:normal;font-family:Georgia;border-style: solid;padding:10px;">Creating matrices with random elements.</h3>

In [17]:
np.random.normal(0, 1, (3, 3)) # Here 0 is mean and 1 is standard deviation 

array([[-0.05826978, -1.06301436, -1.29339595],
       [-2.24043126, -0.11533835, -0.66403868],
       [-0.38438528, -0.49967721, -2.40806047]])

In [37]:
# randint(low, high, size, dtype) , high is exclusive, but low is inclusive.
np.random.randint(1, 10, (3,3))

array([[2, 9, 6],
       [5, 9, 1],
       [5, 8, 3]])

In [19]:
# random will create an array of r * c with items randomly picked b/w 0 and 1.
np.random.random((2,3))

array([[0.91958971, 0.36501128, 0.13770614],
       [0.77538957, 0.56982112, 0.6670393 ]])

In [24]:
np.random.randint(1, 100, size=10)

array([58, 46, 93, 94, 72, 67, 79, 71,  9, 93])

In [25]:
# Give me a random integer from range 1 to 100.
np.random.randint(1, 100)

47

In [38]:
# Give me a 1d array filled with random numbers selcted from range 0 to 2 (2 being exclusive)
np.random.randint(low=0, high=2, size=3)

array([1, 1, 1])