<h1 style="color:black;font-weight:normal;font-family:Georgia;"><u>This notebook is to try python methods, evalute outcomes over numpy arrays</u></h1>

In [1]:
import numpy as np
import IPython as IP

<h1 style="color:black;font-weight:normal;font-family:Georgia;">Properties associated with a np array</h1>

In [23]:
narr_rand = np.random.randint(1,10, (3,3))

In [34]:
print('Dimension of array: ', narr_rand.ndim)
print('Shape of array: ', narr_rand.shape)
print('Data Type of array: ', narr_rand.dtype, end='\n\n')
print('Size of array (as in how many elements): ', narr_rand.size)
print('Size(in bytes) of one array element', narr_rand.itemsize, end='\n\n')
print('Total size(in bytes) of array: ', narr_rand.nbytes)

Dimension of array:  2
Shape of array:  (3, 3)
Data Type of array:  int64

Size of array (as in how many elements):  9
Size(in bytes) of one array element 8

Total size(in bytes) of array:  72


<h3 style="color:black;font-weight:normal;font-family:Georgia;"><span style="font-weight:bold">Goal:</span> Try in-build standard methods available in python</h3>
<p><span style="font-weight:bold">Note: </span> List Methods like pop, index, insert are not available in np type array.</p>

In [35]:
narr_nums = np.array(range(1,11))
narr_chr = np.array(['a', 'b', 'c', 'xyz'])
narr_matrix = np.random.randint(1,10, (3,3))

In [4]:
# Reversed method
rev_arr = reversed(narr_nums)
for item in rev_arr:print(item)

10
9
8
7
6
5
4
3
2
1


In [3]:
# Python sum method
sum(narr_nums)

55

In [5]:
# Slicing an array
narr_chr[::-1]

array(['xyz', 'c', 'b', 'a'], dtype='<U3')

In [6]:
# Indexing.
narr_chr[-1]

'xyz'

In [7]:
# Try to merge two np arrays(having diff type of members) using Python idealogies.
try:
    narr_chr + narr_nums
except np.core._exceptions.UFuncTypeError:
    print('All arrays should have the same dtype')

All arrays should have the same dtype


In [60]:
# Lets see what happens if we use list() on an np array.
our_list = list(narr_chr)
print(our_list)
print(type(our_list))

['a', 'b', 'c', 'xyz']
<class 'list'>


<h1>Array Manipulation</h1>

<h3>Changing an array element in a 2d array</h3>

In [37]:
print(narr_rand[0, 0])

9


In [40]:
narr_rand[0, 0] = 99
print(narr_rand)

[[99  8  9]
 [ 9  6  3]
 [ 5  7  3]]


<h2>Slicing of multi-dimension array</h2>

In [41]:
# Two rows two column
narr_rand[:2, :2]

array([[99,  8],
       [ 9,  6]])

In [42]:
# All rows, two columns
narr_rand[:, :2]

array([[99,  8],
       [ 9,  6],
       [ 5,  7]])

<h2>Accessing array elements</h2>

In [46]:
# All rows, first column
narr_rand[:, 0]

array([99,  9,  5])

In [45]:
# All columns, first row
narr_rand[0, :]

array([99,  8,  9])

<h2>Reshaping Arrays</h2>
<p>You can create another dimension array from one type using reshape() method.

In [54]:
# We create a One Dim array on int type
narr_my_fav_numbers = np.array([20, 25, 40, 50, 80, 99, 111, 555, 600], dtype=int)
print('Dimension:', narr_my_fav_numbers.ndim)
print('Shape:', narr_my_fav_numbers.shape)

Dimension: 1
Shape: (9,)


In [55]:
# Lets reshape it to a 3 * 3 matrix from this array.
narr_my_fav_numbers.reshape(3,3)

array([[ 20,  25,  40],
       [ 50,  80,  99],
       [111, 555, 600]])

<h2>Array Concatenation</h2>
<p>Different ways to merge two arrays.</p>

In [58]:
mer_x = np.arange(1,4)
mer_y = np.arange(4,7)
mer_z = np.arange(7,10)
np.concatenate([mer_x, mer_y, mer_z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<h2>Splitting an array</h2>

In [72]:
# Split an array in N parts.

print(narr_my_fav_numbers)
np.split(narr_my_fav_numbers, 3)

[ 20  25  40  50  80  99 111 555 600]


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [78]:
# Split vertically, a 2d array in two parts.
top, bottom = np.vsplit(np.arange(16).reshape((4, 4)), [2])
left, right = np.hsplit(np.arange(16).reshape((4, 4)), [2])
print(top)
print(bottom)
print(left)
print(right)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
